### ISSUE TITLE
Handling Pattern categories?

### ISSUE THREAD

**Issue by jasonrohrer** [Kazetsukai/onetech#103]
It seems like some pattern category transitions aren't being shown.

For example, all dead puppies decay into nothing, but it's only shown for the wolf puppy.  However, other parts of that same pattern (puppy becoming hungry over time) are working correctly.

**Comment by ryanb** [comment]
The code to generate transitions from patterns is a bit tricky. Probably a bug in there somewhere. I'll look into it when I get a chance.

**Comment by ryanb** [comment]
This has been fixed now.

**Comment by ryanb** [comment]
Hmm I don't think this is solved. There are some extra transitions which are not correct. For example, lapis shouldn't convert to vermillion:

https://onetech.info/1892-Bowl-of-Lapis-Lazuli
