### ISSUE TITLE
Deadly Snowball

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#137]
The snowball is marked as deadly but it only slows the player down.

Look for a transition with “sick” which marks the item as non-lethal. Also change how the death transitions look. Consider adding a decay transition of 40 seconds into death on the non-sick objects.

See [this issue](https://github.com/jasonrohrer/OneLife/issues/176) for more details.

**Comment by Kazetsukai** [comment]
Snowball - Just Thrown appears to still be deadly

**Comment by ryanb** [comment]
Hmm, I'll reopen this to check `transitionsToward` for `sick` object as well.
