### ISSUE TITLE
Changing process script without running build breaks production

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#18]
If I make a pull request which changes the process script and therefore the static dir, and do not run the build script, it will break production due to a build which is out of date with static.

Here are a few solutions.

1. Always run the build script when changing static.
2. Make a `develop` branch that changes are merged into and then merge into master after running build. 
3. Add a `static-dev` directory which is copied to `static` when running build. This can be in `.gitignore` to keep PR size down.
4. Dynamically generate static content in development.

My favorite option is 3 because it would keep PR size smaller but it means you would need to run the process script after pulling changes to test them.

Which do you prefer?

**Comment by Kazetsukai** [comment]
Makes sense. Requiring someone to revert static to make a commit is a little heavy handed. 3 sounds good to me also.

**Comment by ryanb** [comment]
@Kazetsukai can you run the build script? The tech tree doesn’t handle the decay feature correctly at the moment.

In future pull requests I will not include static changes (option 3)

**Comment by Kazetsukai** [comment]
Yep, trying now. Not at my mac, so having to fake my way into a linuxy environment through docker on windows machine.

**Comment by Kazetsukai** [comment]
Scratch that, don't need to run process since you already did. Building now.
