### ISSUE TITLE
Duplicate transitions

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#2]
As [reported here](https://onehouronelife.com/forums/viewtopic.php?pid=2653#p2653), some objects have duplicate transitions when combining the same object together. For example thread or reeds.

**Comment by Kazetsukai** [comment]
Yep, need to have a closer look at the actual transitions causing those, to see what (if anything) differentiates them. If that is information relevant to user then it should be surfaced, otherwise we can de-dupe the transitions.
