### ISSUE TITLE
Dependency versions, Typescript and Vue 3.

### ISSUE THREAD

**Issue by connorhsm** [Kazetsukai/onetech#215]
If there's interest for onetech, I've been running twotech with Node 18 and dependencies as up to date as possible for some time now.

The two `package.json` files provide most of the required context, but I recall there were various breaking changes to Canvas, Webpack, Babel and more.
- https://github.com/twohoursonelife/twotech/blob/master/package.json
- https://github.com/twohoursonelife/twotech/blob/master/process/package.json

@mtklass is also kindly finishing up migrating the project over to Typescript and Vue 3 via [this PR](https://github.com/twohoursonelife/twotech/pull/61).

Would be happy to assist further or PR directly if there's interest.

**Comment by ryanb** [comment]
@connorhsm I'm uncertain when I will get around to updating onetech due to my busy schedule. It will likely stay on Vue 2 unless there is some critical issue that requires upgrading.

Since @Kazetsukai is the true owner of this repo I'll defer to him on adding other maintainers if he wants.

**Comment by Kazetsukai** [comment]
Same situation here, too many side projects on the go at the moment to give this much attention these days. Happy to go either way, main consideration on my side would be stability since it is linked to from Jason's site.

**Comment by connorhsm** [comment]
No worries, I won't commit to it myself for the time being.
