### ISSUE TITLE
Suggestion: Tech Tree

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#3]
It would be very helpful to see all steps necessary to craft something on a single page. You could show a tech tree [similar to this](https://onehouronelife.com/forums/viewtopic.php?pid=2201#p2201). Perhaps add a "Tech Tree" button underneath the object info.

Some objects have multiple "from" transitions. For these you could create a formula for selecting the most common case. For example, to make a [Long Straight Shaft](https://kazetsukai.github.io/onetech/#67/Long-Straight-Shaft) you want to show crafting a sharp stone with a straight branch.
* Ignore timed transitions
* Ignore empty hand transitions
* Avoid circular dependencies
* Prefer transitions that result in only that object

Some special coding might still be required for certain cases. I can work on a pull request for this if you like.

**Comment by Kazetsukai** [comment]
I have given this a fair bit of thought. If you have a look, I made a first failed attempt at processing the data for calculating the "recipe depth" of each item from the natural items here: https://github.com/Kazetsukai/onetech/blob/50a06e38231bf6bddd163afd3299c058384d299b/process/process.js#L355

My first attempt led to me coding myself into a bit of a corner, so it would need to be redone from scratch. The minimum depth of a given item is going to be the max of the minimum depths of the two items that create it, or the minimum of those maximums if there are more than one recipe that will reach that item. By breadth first searching out it should be possible to avoid circular loops (a minimum depth recipe should hopefully strictly dominate any higher depth recipes) but my brain was a bit frazzled by the end of that code so I left it aside for a bit.

**Comment by ryanb** [comment]
@Kazetsukai I took a crack at this today with some success. Here's what it looks like:

<img width="1040" alt="screen shot 2018-03-13 at 2 00 18 pm" src="https://user-images.githubusercontent.com/161/37369687-15db41aa-26c7-11e8-8b7f-f89fc5341d95.png">

The code for choosing a transition is pretty rough but it works fairly well:

```javascript
return _.sortBy(this.object.transitionsTo, function(transition) {
  var weight = 0;
  if (!transition.actor || !transition.target) {
    weight += 1;
  }
  if (transition.newActor) {
    weight += 1;
  }
  if (transition.decay) {
    weight += 1;
  }
  if (transition.newTarget != object) {
    weight += 1;
  }
  return weight;
})[0];
```

I am finding some cases where there is no obvious way to choose a transition. For example the [firebrand](https://kazetsukai.github.io/onetech/#248/Firebrand) has many ways to be lit. Ideally it would show the Fire, but how would it decide this over an adobe oven? Perhaps the one with the shallower tree?

I'm considering arrows on the left/right side of each combination in the tree allowing one to flip through transitions. What do you think?

**Comment by Kazetsukai** [comment]
Right, so a nice heuristic for which transition to pick? That's an interesting idea. I was aiming to base it off distance to natural objects, where natural objects are objects with a non-zero mapChance (things that can spawn in the map). It definitely seems like it would get tricky with things like "you need kindling, which tree should you get it from?" although your idea of being able to toggle between alternatives with little arrows would solve that nicely I think.

Looks pretty nice, edge cases concern me a little and I shudder to think what the pine door tech tree would look like, but that stone hatchet tech tree is quite compelling. I like it.

**Comment by ryanb** [comment]
@Kazetsukai I updated my comment before seeing your reply. I think calculating the cost of an item based on the minimum depth to craft would be really helpful in choosing the transition. For example, to make kindling it is preferring a steel ax over a hatchet. That would also solve the firebrand choosing the oven over a fire.

BTW, here's the pine door tech tree. I'm only showing 4 depth. I figure they can select another object to see a tech tree of that one.

<img width="1041" alt="screen shot 2018-03-13 at 2 23 53 pm" src="https://user-images.githubusercontent.com/161/37370684-3726fdb0-26ca-11e8-8647-841806570dd5.png">

**Comment by Kazetsukai** [comment]
Love it, limiting depth to 4 is a great idea. For a first cut it might even be sensible to just count the number of nodes at each layer and cut depth back until the width is sensible.

If we made it obvious that you can scroll, including a left click to pan for desktop users, scrolling overflow should work well.
