### ISSUE TITLE
Support weapon transitions

### ISSUE THREAD

**Issue by Kazetsukai** [Kazetsukai/onetech#32]
Weapon transitions are a nightmarish hack that involve more than one transition per attack: https://github.com/jasonrohrer/OneLife/blob/975ae127baebac8970a7f7cdea15e19bf41034b3/server/server.cpp#L5065

**Comment by UncleGus** [comment]
In case it helps:
-1 in the transition title indicates empty ground/nothing.
0 in the transition title indicates a player.
0 in the transition file contents indicates ground/nothing.
If 0 is the target of the transition and it produces 0, then that's the default kill transition, which produces a grave.

**Comment by Kazetsukai** [comment]
To elaborate: If the deadly distance is set on something, and you attack with it, it looks for two transitions that use the weapon and target "0". One of them is marked "last use on target" and one is not. The "last use on target" transition indicates how the weapon will change, and what grave is created. The other one indicates what projectile will be left on the grave/on the ground. It is possible that for our purposes we could ignore the second transition (filter out any weapon transitions that are last use on target), although to be strictly correct we would need to merge the transitions or something similar

It seems like a lot of effort just to show that bow and arrow leaves an arrow in the grave, so might be worth just filtering that second transition out for now.

**Comment by ryanb** [comment]
Isn't the second transition (leaving arrow on ground) a valid one if the bow misses? Or does the arrow disappear? I haven't used the bow much in game.

**Comment by ryanb** [comment]
Looks like the [bow can miss](https://github.com/jasonrohrer/OneLife/commit/745b6cf1d826d62e0585fc51e971f61fa40c732e#diff-6e2abdb2563c0ce3bc629d9a9bccab7bR35). In that case should we keep both transitions?

**Comment by Kazetsukai** [comment]
I would lean towards not keeping it, mostly just because it doesn't seem
like a useful transition to show. How important is it to tell people that
the arrow can interact with the ground?

**Comment by ryanb** [comment]
Looks like the bow also transitions to a [just shot bow](https://kazetsukai.github.io/onetech/#493/Yew-Bow---just-shot). Not sure the significance of that, but either way I think a lot of this is changing tomorrow. We can figure out what to do when that happens.
