### ISSUE TITLE
Show differences between versions

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#36]
Some way to show what has changed between versions would be handy. We could show:

* New objects
* New transitions between objects
* Stats that have changed for existing objects (for example, use amount, clothing and food values)

**Comment by ryanb** [comment]
Just thinking about how to implement this. The process script could support a version number.

```
node process.js v71
```

It would then switch to the tagged version of the repo and run the process script on it. This would also add its version to a `static/versions.json` and add a `static/versions/#version.json` file with details on what has changed compared to the previous version.

We could add a way to generate this for all previous versions as well so we have a nice history of the changes.

**Comment by Kazetsukai** [comment]
I was imagining something that would get the list of releases, pull down
directory listings for each release, and just use the filename to work out
when an object or transition was first seen. Should keep around the data on
which versions have been checked so it could be run again only retrieving
the latest releases.

**Comment by ryanb** [comment]
If we checkout the OneLifeData repo and do `git tag -l` we can get a list of versions. Switching between versions would be quicker than downloading each release separately, but maybe not ideal for comparing them.

**Comment by Kazetsukai** [comment]
Fair point. If we just do a "is this file present" check at first then that
would work really well.

**Comment by ryanb** [comment]
From the user's perspective, what would be the best interface for this? Should we attempt to show every transition and stat change? Or should we simply list out just the objects which have been added?

The latter would be much easier to do, but not certain what is best.

**Comment by ryanb** [comment]
See PR #42 for a first crack at this. It assigns the version to each object of when it was added. This means we can sort by the version and filter it easily. However it will not show transition or stat changes.

**Comment by ryanb** [comment]
@Kazetsukai is this still necessary since we now sort objects by their version? The most important thing is seeing what objects are new.

**Comment by ryanb** [comment]
This feature is in place, just commented out. I will I comment it. :)

**Comment by ryanb** [comment]
Each object now says when it was added. Closing this for now. We can re-open or make a new issue if we want a more extensive version difference.

**Comment by ryanb** [comment]
Reopening because this will be coming soon.

**Comment by Kinrany** [comment]
> From the user's perspective, what would be the best interface for this? Should we attempt to show every transition and stat change? Or should we simply list out the objects which have been added?

You could have a list of objects that have been either added or changed, and for each have a drop-down menu with new transitions.
