### ISSUE TITLE
Number of "junk" transitions

### ISSUE THREAD

**Issue by Kazetsukai** [Kazetsukai/onetech#41]
There are quite a few transitions showing that don't make sense. Would be good to hide these, or figure out what they actually mean. With expansion of categories this has become a little bit worse.

Two seemingly identical transitions for flooding a pond with a goose in it, there are more transitions for the state where there is a feather next to the pond. Maybe possible when there are categories involved to bundle them up into one transition and provide arrows? My concern is if we get categories interacting with categories, we end up with a cartesian product of transitions that could explode in number.
![image](https://user-images.githubusercontent.com/935494/38396735-c7d898ac-398d-11e8-8a64-ba899c0963c4.png)

Also in cases like this, we have "Clay bowl with water + empty ground = clay bowl + empty ground". Is this interaction with another human? No idea what causes this, but empty ground -> empty ground transitions might be a good idea to hide for now. 
![image](https://user-images.githubusercontent.com/935494/38396831-3fb1a724-398e-11e8-9512-779a5dacd7c1.png)

**Comment by ryanb** [comment]
I think the latest category pull request resolves the duplicate transitions related to categories. Not certain about the empty ground issue though.

**Comment by ryanb** [comment]
> Two seemingly identical transitions for flooding a pond with a goose in it, there are more transitions for the state where there is a feather next to the pond.

This one is fixed properly.

> Also in cases like this, we have "Clay bowl with water + empty ground = clay bowl + empty ground". Is this interaction with another human? No idea what causes this, but empty ground -> empty ground transitions might be a good idea to hide for now.

I tried removing transitions with empty targets however the [rabbit bones transition](https://kazetsukai.github.io/onetech/#197/Cooked-Rabbit) is an important one to keep. The only difference I found between this and the junk transitions is `actorMinUseFraction` and `targetMinUseFraction` are set to 0 in their transition file.

I put a bit of a hack in to check if that is a string value (set from the file). The end result works but this could cause issues down the road.

If we can figure out the real cause for these transitions and display them properly that would be better. Feel free to re-open this issue in that case.
