### ISSUE TITLE
Incorrect water transitions

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#44]
Water container transitions are still not correct. For example, the [cistern](https://kazetsukai.github.io/onetech/#672/Cistern) has no transition from empty clay bowl to water bowl.

The "Empty Portable Water Source" transitions maintain their category id so it incorrectly looks like a tool. However the `reverseUseTarget` is set to `1` which I assume means this is supposed to reverse the object state from empty/filled. Is this correct? I'd need to dive into the code to see how it works.

This goes along with issue #41.

**Comment by Kazetsukai** [comment]
Yes, I believe reverseUse means to add a use to something with multiple uses, possibly reversing the "lastUseTarget" or "lastUseActor" transition

**Comment by Kazetsukai** [comment]
I'm not sure if reverseUseTarget will reverse a "Last Use of Target" transition, but it is definitely used by transitions that add one charge to something (berry bushes spawning berries and ponds being refilled)

**Comment by ryanb** [comment]
I will need to dive into the code to figure out how water transitions work. I'm not seeing a transition that toggles the filled/empty water state for cisterns and wells.

**Comment by Kazetsukai** [comment]
My current understanding is that there will be two transitions that can use a well for example:

- Transition from well to well
- Transition from well to dry well, marked as _LT (last use of target)

The last use of target transition is the one used when the target has run out of uses

**Comment by ryanb** [comment]
The tricky part is the portable water source category. Like the water pouch. When this interacts with the well it does not transition between full/empty.

**Comment by ryanb** [comment]
I talked with Uncle Gus on Discord. The water pouch transition which goes from `-1` to `0` is considered a generic transition which is applied when another transition succeeds. This means I need to merge this transition with the category transitions to make the water pouch fill properly.

**Comment by ryanb** [comment]
The way the tools break in the next update also use generic transitions. It is a last-use transition which targets the ground and results in a broken tool.

This one will be trickier to fix because we can’t simply merge it onto the existing transitions.

One option is to duplicate each existing transition with the last use transition. Another option is to show “anything” as the target for a generic transition.

**Comment by ryanb** [comment]
I rewrote the transition importer to handle generic transitions and murder transitions. It now adds the arrow to the murdered grave.

**Comment by ryanb** [comment]
By the way, I just duplicated each transition for the broken tools. It leads to a long list of transitions, but I think when we tackle the recipe card improvement we can hide most of the transitions with a link to expand them
