### ISSUE TITLE
Lack of information on object list

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#49]
As suggested in #43, it would be nice to add badges to the objects in the object list. This would be an icon followed by a value. Here are some icon suggestions from font-awesome.

* Clothing
  * [allergies](https://fontawesome.com/icons/allergies?style=solid)
  * [male](https://fontawesome.com/icons/male?style=solid)
* Food
  * [utensils](https://fontawesome.com/icons/utensils?style=solid)
* Tools
  * [wrench](https://fontawesome.com/icons/wrench?style=solid)
  * [gavel](https://fontawesome.com/icons/gavel?style=solid)
* Heat Sources
  * [fire](https://fontawesome.com/icons/fire?style=solid)
  * [gripfire](https://fontawesome.com/icons/gripfire?style=brands)
* Water Sources
  * [tint](https://fontawesome.com/icons/tint?style=solid)
* Natural
  * [tree](https://fontawesome.com/icons/tree?style=solid)

Not too happy with the Clothing or Fire options. Might need to use our own images.

**Comment by Kazetsukai** [comment]
There are definitely appropriate icons in unicode, is there a font which has the unicode icons in monochrome? https://emojipedia.org/t-shirt

**Comment by ryanb** [comment]
You can use `filter: grayscale(100%)` in CSS to get a black and white emoji. I think Safari requires `-webkit-` prefix.

**Comment by Kazetsukai** [comment]
I was thinking like NotoEmoji https://www.google.com/get/noto/#emoji-zsye

**Comment by ryanb** [comment]
Aha, nice. One thing to watch out for is the file size. Is it worth downloading a 200KB+ font for a few icons? Might be alright.

**Comment by ryanb** [comment]
As long as the licensing allows it, we could grab the SVGs of the icons we want and use those directly.

**Comment by Kazetsukai** [comment]
Good points. I think Noto license was pretty liberal?
