### ISSUE TITLE
Filters list is cramped on mobile

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#50]
![f181e0ae-bb23-4a1f-b2cd-70bf9431c8d6](https://user-images.githubusercontent.com/161/38578972-5e9cf2a4-3cba-11e8-9270-147c5d86b99d.png)

The list doesn’t look right. It is too tight for the wide text and the close button overlays.

Perhaps truncate the text or turn it into one per line on mobile.

Also the hover effect should be removed on mobile for both lists since it interferes with touch.

**Comment by ryanb** [comment]
It now truncates the filter text if it is too long and makes it smaller on mobile.

<img width="381" alt="screen shot 2018-04-18 at 10 45 01 am" src="https://user-images.githubusercontent.com/161/38949010-fdbb2e64-42f5-11e8-9e3e-a6eda31189b2.png">

**Comment by Kazetsukai** [comment]
Nicely done
