### ISSUE TITLE
Request: option to point at a data directory locally instead of downloading

### ISSUE THREAD

**Issue by UncleGus** [Kazetsukai/onetech#53]
I have my forked onetech in a sibling directory to my data directory, so it feels kind of silly doing a git push and then downloading it all again in almost the same place.

This is just a very nice to have though; it's not like I am running out of disk space or anything.

**Comment by Kazetsukai** [comment]
Data directory might not be straightforward because it would break the version checking stuff, but could totally point at a local git repo which is what that folder would be anyway.

**Comment by ryanb** [comment]
@UncleGus you can now override the local git path:

```
export ONETECH_PROCESS_GIT_PATH="/path/to/custom-ohol-data"
```

Then you don't need to run `download` when you process since it will already be up to date.
