### ISSUE TITLE
Some questions and feature suggestion

### ISSUE THREAD

**Issue by naveed-ahmad** [Kazetsukai/onetech#59]
This is a great project, thanks to you guys for introducing me to vuejs. Learned quite a few things.  

Last weekend spent few hours and crafted an android app using Cordova, vuejs, framework7 and very happy with the results.  Borrowed most of the code from this project. Hopefully, you don't have any issue with that?  

Also added a couple of new features in this app, like filter object with version( very handy to see what's new stuff in the latest release). See related objects( like list all kind of pies on Cooked Berry Pie page). 

This Android app has reused components from this project but the overall layout of the app is very different from this project. Now if we want "version filter" and "related objects" features here, ill love to send the PR. Thoughts?

**Comment by Kazetsukai** [comment]
Awesome, yeah no worries, I consider the code in this repo to have inherited the philosophy @jasonrohrer takes towards the game code itself (effectively public domain, I will certainly not be complaining if anyone uses anything in it for whatever purposes).

I'm not sure about the version filter, I believe we are sorting by version on the front page to achieve a similar effect.
For the related objects, that sounds like an interesting idea, as long as it is powered off data that can be generated automatically and doesn't rely on handmade lists.

**Comment by ryanb** [comment]
Sounds awesome @naveed-ahmad.

> I'm not sure about the version filter, I believe we are sorting by version on the front page to achieve a similar effect.

I recently changed the sort order to use object id (descending) since it roughly follows the version and further groups similar objects. I have some further ideas on showing differences between versions but not certain how much it will be worth it.

Regarding related objects, I considered adding this but thought it would overlap too much with the transitions to/from the object. I'd love to see some examples of this in action though.

**Comment by naveed-ahmad** [comment]
Sorting by version number works great for home page listing, but it doesn't answer "which new objects were released in version X". User have to go through each object to see its version, for mobile devices it goes worst. 

Sorry that's my openion, and I'm fine we don't want this feature here. 

For related object, i've added `related_objects` field and these values are calculated based on object category.  

```json
{
"id":"645",
"name":"Fed Grizzly Bear",
"related_objects":["654","632", "631","628"],
"transitionsToward"::...
}
```
631: Hungry Grizzly Bear
628: Grizzly Bear
632: Shot Grizzly Bear
654: Shot Grizzly Bear - Attacking

Then showing the related object as simple list when user click on "Info" icon( simple fontawesome icon but we need a better icon for related objects). ill start moving some code from this android app and send PR in few days.

**Comment by ryanb** [comment]
Do you have any screenshots of the app? I'd love to see how the version information and related objects are presented.

**Comment by ryanb** [comment]
Closing this since it is covering multiple issues.

@naveed-ahmad could you create a separate issue for each suggestion? This way we can discuss them separately. Thanks!
