### ISSUE TITLE
Animal filter

### ISSUE THREAD

**Issue by naveed-ahmad** [Kazetsukai/onetech#60]

**Comment by Kazetsukai** [comment]
In our UI it will take a little bit of work to have more than 6 filters laid out nicely. Perhaps if we get up to 9 different categories we want to filter on, we can add this. For now, animals come under the "Natural" filter, and I don't think there are enough animals/natural objects to justify a new category yet.

Worth keeping an eye on as the project continues though, and as Jason adds a lot more objects to the game we can definitely rethink this.

**Comment by ryanb** [comment]
I originally had an animal filter but couldn't figure out the best attributes to filter upon. For example, the canada goose pond should be an animal but not the ice hole in the ground. There isn't much distinguishing the two.

**Comment by Kazetsukai** [comment]
My gut feeling on this is that there would be timed transitions with no
instigator that cause a move action, and these would be the things that are
animals. Then you could treat any object that can end up transitioning to
one of these marked animals without involving another animal in the
transitions as also being an animal. It would be far more effort than it is
worth I think though. Would make more sense to just go to the game wiki and
have a page of animals there instead.
