### ISSUE TITLE
Object images are too small

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#61]
Most object images have a lot of white space around them. This makes them appear tiny when browsing transitions and recipes.

Should the sprite generator remove the white space? Perhaps `ObjectImage.vue` should then only shrink the images and not enlarge them. This way a gooseberry does not look huge.

**Comment by Kazetsukai** [comment]
Yeah, this was something that was a little tricky to get right. At the
moment the sprite generator works out the size the output image should be
based on the sizes of the input sprites and how they are rotated, with a
minimum size of 128 to prevent things like the gooseberry getting too big.
It could possibly be doing a better job of cropping for sprites above
128x128 with an Imagemagick pass or similar afterwards. Feel free to give
it a shot and see how it looks if you like.

**Comment by ryanb** [comment]
I think most images above 128 look alright. It is the 128 minimum which causes the whitespace. What about a lower minimum?

**Comment by Kazetsukai** [comment]
Could work, give it a shot. Didn't have any particular reason for that
number except that I didn't want the images too much bigger on the details
pages. But we could probably shrink the images on the details pages now
anyway.
