### ISSUE TITLE
Recipe counts are sometimes off

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#64]
Sometimes the count is off on the recipe ingredients.

* [Stone Hatchet](https://kazetsukai.github.io/onetech/#71/Stone-Hatchet/recipe) shows 6 stones are needed. It gets confused when a tool is consumed (such as a sharp rock being used to craft the hatchet).
* [Adobe Kiln](https://kazetsukai.github.io/onetech/#238/Adobe-Kiln/recipe) shows 6 clay deposits are used. It does not factor in items with multiple uses
* [Shallow Well](https://kazetsukai.github.io/onetech/#662/Shallow-Well/recipe) shows 1 round stone is necessary instead of 10. It should also show 10 stones are used to make the pile.
* [Wool Sweater](https://kazetsukai.github.io/onetech/#585/Wool-Sweater/recipe) shows it is necessary to craft 3 arrows to make 3 wool balls. It does not detect that we get an arrow back from the mouflon.

Any others that are different than these situations?

**Comment by Kazetsukai** [comment]
That 6 clay deposits is strange, I can't think why it would be doing that.
It should only need 3 uses of one clay deposit right? Showing it as Clay
Deposits x3 when you need 3 uses is fine IMO, but I don't get why it is 6

**Comment by Kazetsukai** [comment]
And yeah for stone hatchet we might need to track "we built this thing, it
is in our 'inventory' until it gets used up" when working out the recipes.
Still don't understand why it is 6 and not 3 (although yes inevitably it
should be 1).

**Comment by ryanb** [comment]
I think the 6 count is a bug in how objects are removed from other steps. It gets complicated when objects are reused across steps.

I might add some unit tests for the process script to duplicate and fix the bugs.

**Comment by ryanb** [comment]
I rewrote the recipe generator to better handle object counts. It still needs some work but it is mostly working.

**Comment by ryanb** [comment]
The [Wooden Door](https://kazetsukai.github.io/onetech/#875/Wooden-Door/recipe) count is now fixed, it shows 2 trees are required.

I don't think I will fix the [Shallow Well](https://kazetsukai.github.io/onetech/#662/Shallow-Well/recipe) issue for now. The stone count gets quite confusing, and it is fairly obvious that multiple stones are required. Feel free to re-open if you want that fixed.
