### ISSUE TITLE
No way to know how many items a container can hold

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#65]
Basket should say it can hold 3 items, cart 4, etc. Perhaps include size information.

Should each item say if it is containable in a basket?

**Comment by Kazetsukai** [comment]
"Holds X items"
Do we have the information to distinguish? i.e. can we say "Holds 4 small
items" "Holds 3 large items"?

We could then say "Small item" or "Large item" etc on the items page,
potentially with a mouseover list of items it can be held in, although that
might be a bit extreme.

**Comment by ryanb** [comment]
I added the "Holds 3 small items" text but didn't add "Small item" or "Large item" information on each page because I thought it clutters it up.

What do you think, should I add that?

**Comment by Kazetsukai** [comment]
Nah that sounds good for now.
