### ISSUE TITLE
Biomes are hard-coded

### ISSUE THREAD

**Issue by UncleGus** [Kazetsukai/onetech#69]
This causes issues when there are new biomes added. But the other problem is that the biomes don't actually have names, so maybe the names could still be hardcoded, but if the name is not supplied, then it could default to the biome number instead.

Biomes are defined in the `ground` folder as a `ground_#.tga` file. Note that `ground_U.tga` doesn't count.

**Comment by ryanb** [comment]
We could show the biome images instead of the names on the object inspector page. Perhaps guess the name when hovering over, but don't crash if it doesn't know.
