### ISSUE TITLE
process.js tries to parse all files in the data folders, including the cache files

### ISSUE THREAD

**Issue by UncleGus** [Kazetsukai/onetech#70]
This is only an issue when pointing onetech at local data files, since these cache files are ignored by git, so won't be included when downloading the data.

Most data folders get cached by the client, server and editor into files called `cache.fcz`. These should be disregarded when processing data files.

**Comment by ryanb** [comment]
I'll make it filter out only `*.txt` and `*.tar` files, whichever it needs.
