### ISSUE TITLE
Poor SEO

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#78]
This isn't very crawler friendly at the moment. Google and others have some trouble with SPAs. Searching something like "one hour one life craft door" has the site show up pretty far down, and doesn't go directly to the page. Some resources:

* https://moz.com/blog/optimizing-angularjs-single-page-applications-googlebot-crawlers
* https://vuejsdevelopers.com/2018/04/09/single-page-app-seo/
* https://vuejsdevelopers.com/2017/04/01/vue-js-prerendering-node-laravel/
* https://github.com/rafrex/spa-github-pages
* https://github.com/isaacs/github/issues/408

**Comment by ryanb** [comment]
Looking into this a bit more, I think the best solution is to use the Vue Router with [History Mode](https://router.vuejs.org/en/essentials/history-mode.html) along with [this GitHub pages workaround](https://github.com/rafrex/spa-github-pages). We can then add a sitemap and ensure there are crawlable links around the whole app. This should resolve the majority of SEO issues.

Alternatively we could mess with prerendering or move away from GitHub Pages to do server-side rendering. Both of these are heavy solutions which I don't think are necessary.

**Comment by ryanb** [comment]
Despite these changes, the pages still aren't showing up in Google. I need to look into this more.

**Comment by ryanb** [comment]
The custom domain is all setup now which will probably improve SEO. I've also setup the site with Google's [Search Console](https://search.google.com/search-console) which will show me what's wrong once it indexes the site (in a day or two).

**Comment by ryanb** [comment]
Looks like Google is reporting a 404 error on a number of pages even though those pages work when I visit. I don't think Google likes the `404.html` hack that is [described here](https://github.com/rafrex/spa-github-pages).

I might put this on a cheap VPS in the near future so we can have true route redirects.

**Comment by ryanb** [comment]
Google Search Console is reporting this about the indexing:

<img width="931" alt="screen shot 2018-06-19 at 12 26 18 pm" src="https://user-images.githubusercontent.com/161/41619713-10e104fe-73bc-11e8-8cec-c03a89a1c413.png">

It is intentionally excluding the URLs because the server reports a 404 status, even though we redirect on the client side and the [SPA hack](https://github.com/rafrex/spa-github-pages) was supposed to work with Google indexing.

I recreated the sitemap to use the `onetech.info?p=...` URL format which will result in no 404s. Let's see if Google likes that.

If this doesn't work, setting up a separate server seems like the only other option.

**Comment by Kazetsukai** [comment]
Using # URLs should still be viable and fine for SEO

**Comment by Kazetsukai** [comment]
Yeah, have run into that. In practice at my workplace it hasn't caused us
SEO problems, although we are moving away from it longer term.
Something cheeky like cloudfront is also possible:
https://keita.blog/2015/11/24/hosting-a-single-page-app-on-s3-with-proper-urls/

**Comment by ryanb** [comment]
> Something cheeky like cloudfront is also possible:

Yeah, Cloudfront would be cheeper than a dedicated VPS, although it would be nice to have a persisted local Git repo + cron job that we can do `git pull` every few minutes and auto-update the site with new content.

We could get fancy and use something like Amazon Lambda and communicate with GitHub through the API to check for changes and request just what we need, however not sure about sprite processing and memory usage. Also sounds like a lot of work to setup. ;)

**Comment by Kazetsukai** [comment]
Again cheeky, but you could probably get away with free tier codebuild.

**Comment by ryanb** [comment]
Interesting. I didn't consider a build service but that might just work.

**Comment by ryanb** [comment]
The app is now fully hosted on a VPS so the 404 hack is no longer necessary. I think this will help with SEO but time will tell.

**Comment by ryanb** [comment]
Moving to a VPS hosted page has helped SEO significantly. Since I have control over the Nginx config I no longer need to do the 404 redirect work-around. Google is still excluding a lot of the URLs in the sitemap, but I don't think there is much more I can do about that for now.
