### ISSUE TITLE
Custom Domain

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#79]
What do you think about a custom domain for onetech, @Kazetsukai? I can help support it.

**Comment by Kazetsukai** [comment]
Definitely open to the idea, but personally haven't had much time to work
on this project recently. If you would like to then go for it.

**Comment by ryanb** [comment]
I looked up some domain names but nothing stood out to me that was available. Closing this for now.

**Comment by ryanb** [comment]
I decided to go with the domain http://onetech.info

@Kazetsukai, would you mind changing the [settings to add this custom domain](https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/)? Please allow non https which should be fine since it is a static site.

In case it matters, I set this up as an A record following [these instructions](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider). It will probably take a few hours to propagate.

I assume GitHub Pages will automatically redirect to this domain when accessing it through the old URL. If not I can setup a redirect through JavaScript.

**Comment by ryanb** [comment]
Thanks for setting this up. Looks like it is working for the most part.

HTTPS should be supported through GitHub with LetsEncrypt, but currently browsers are reporting the certificate is from "www.github.com" which doesn't match "onetech.info". Here are the [docs for troubleshooting HTTPS](https://help.github.com/articles/troubleshooting-custom-domains/#https-errors) which says:

> After updating any A record IP addresses, you must remove and re-add your custom domain to the repository you’re using to publish your Pages site to trigger the process of enabling HTTPS

I wonder if the DNS wasn't propagated at the time it was added.

@Kazetsukai do you mind re-adding the custom domain when you have time? Thanks.

**Comment by Kazetsukai** [comment]
Done. It mentions on the setting page that it can take 24 hours for the
certificate to be issued, so I'll try to pop in tomorrow to check if that
has worked and set enforce HTTPS if it does.

**Comment by ryanb** [comment]
Thanks. There's another strange issue where a request only works some of the time. This either has to do with GitHub's redirecting or my domain provider. Should be fixable on my end.

**Comment by ryanb** [comment]
Turns out my name server is adding its own `A` record causing it to fail randomly. I've changed it to a different name server which should fix this once it propagates in an hour or so.

**Comment by ryanb** [comment]
Looks like https is enforced now, thanks! Closing this.
