### ISSUE TITLE
Show Unreleased Content

### ISSUE THREAD

**Issue by ryanb** [Kazetsukai/onetech#88]
It might be nice to show upcoming content before it is released.

- [ ] Add an "Unreleased" version to the top of the versions page which is hidden by default
- [ ] Add a "Show Unreleased Content" link at the top of the Versions page which shows that version
- [ ] Hide unreleased content from the home page

**Comment by ryanb** [comment]
This will be a little trickier than I expected because what if the unreleased changes cause an object or transition to be removed? I want those to still show up in the main database.

Basically I should only show unreleased content on the versions page which means I need to check out the latest tag before importing the initial set of objects.

**Comment by ryanb** [comment]
Instead of trying to integrate unreleased content into the main site, consider making it a separate subdomain such as `edge.onetech.info`. This could use a separate `static-edge` directory.

**Comment by ryanb** [comment]
Hmm, it doesn't look like GitHub Pages supports having both a domain and subdomain:

https://help.github.com/articles/troubleshooting-custom-domains/#unsupported-custom-domain-name

We could use a path instead (https://onetech.info/edge) however we would then need to improve the route handling to account for this optional path. Alternatively I could make a separate GitHub repo for the edge domain, but that might be difficult to sync the two.

**Comment by ryanb** [comment]
My main concern now is keeping this repo a reasonable size. If I have a `static-edge` directory that is generated on each commit, the `objects.json` file alone will take up a lot of space due to it changing each time. I think this repo has officially outgrown GitHub Pages. Moving to a true host will solve several issues.

* Resolve the SEO issues (404 redirect hack)
* Support `edge.onetech.info` subdomain over https
* No need to store assets in this repo, it can be purely the JavaScript changes
* No need to rebuild the static JS files for each change to take place

I'm willing to pay for a cheap host for a year or two. If the time comes I no longer want to pay for hosting, I can always switch it back to GitHub Pages.

**Comment by Kazetsukai** [comment]
Sounds like a good idea, just in a basic Linode or Vultr mode. One
consideration is CDN, is there a good cheap thing we can use the will allow
us to have good speeds around the world still?

**Comment by ryanb** [comment]
@kazetsukai, I am currently hosting it on a $5/month droplet on Digital Ocean. They do offer a CDN for an additional $5 per month. Not sure if that will be worth it or not. I will see if any complain about the speed.

Closing this since the app is now fully running on the VPS. It is still using fully static files, so updating build.js is still necessary. I might try doing dynamic node.js hosting soon.
